name: cattyled_app
description: "CattyLED Control Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_xlider: ^3.5.0
  mqtt_client: ^10.5.1
  bloc: ^8.1.4
  get_it: ^8.0.3
  logging: ^1.3.0
  connectivity_plus: ^6.1.1
  typed_data: ^1.4.0
  flutter_bloc: ^8.1.6
  async: ^2.11.0
  flex_color_picker: ^3.6.0
  qr_flutter: ^4.1.0
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Semibold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
